services:
  - type: web
    name: hackathon-evaluator
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT wsgi:app
    plan: free
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: LEADERBOARD_CSV_PATH
        value: ../data/leaderboard.csv