# Hackathon Evaluator Configuration
---
# Server settings
server:
  host: "0.0.0.0"
  port: 5001
  debug: true
  secret_key: "dev-secret-key-change-in-production"

# Evaluation settings
evaluation:
  criteria_weights:
    accuracy: 0.4
    performance: 0.3
    completeness: 0.3
  
  # Mock scoring parameters (customize for your hackathon)
  scoring:
    base_score_range:
      min: 0.6
      max: 0.95
    completeness_bonus_max: 0.1
    performance_time_threshold: 10.0  # seconds
    performance_memory_threshold: 1000.0  # MB

# Leaderboard settings
leaderboard:
  max_displayed_participants: 100
  auto_refresh_seconds: 30

# Test data generation settings
test_data:
  seed: 42  # Fixed seed ensures all participants get identical test data
  dataset_path: "data/jlr_vehicle_configurations.csv"
  
  # Similarity thresholds for evaluation
  thresholds:
    high_similarity: 0.85  # Cosine similarity threshold for "very similar" configs
    low_similarity: 0.30   # Cosine similarity threshold for "dissimilar" configs
    single_option_diff_min: 0.75  # Min similarity when only 1 option differs
    
  # Test case weights (must sum to 1.0)
  test_weights:
    price_extremes: 0.15           # Test 1: Most vs least expensive
    single_option_difference: 0.15  # Test 2: Configs differing by 1 option
    model_year_sensitivity: 0.10    # Test 3: Same config, different model year
    color_sensitivity: 0.10         # Test 4: Same config, different color
    trim_level_similarity: 0.10     # Test 5: Same vehicle/year, different trims
    vehicle_line_separation: 0.10   # Test 6: Different vehicle lines
    derivative_clustering: 0.10     # Test 7: Same derivative should cluster
    feature_count_correlation: 0.10 # Test 8: Feature count vs similarity
    transitivity: 0.05              # Test 9: A~B, B~C => A~C
    cross_year_comparison: 0.05     # Test 10: Same config across years

# API settings
api:
  timeout_seconds: 30
  max_payload_size_mb: 10
  rate_limit_per_minute: 100

# Deployment settings
deployment:
  environment: "development"  # development, staging, production
  log_level: "INFO"
  enable_cors: true
  
# Production overrides (for Render deployment)
production:
  server:
    debug: false
    secret_key: null  # Will use environment variable
  deployment:
    environment: "production"
    log_level: "WARNING"